### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by ZTurboX** [yuanxiaosc/Entity-Relation-Extraction#1]
请问可以提供一下完整的训练数据集吗，我没有参加比赛，所以下载不了

**Comment by yuanxiaosc** [comment]
> 请问可以提供一下完整的训练数据集吗，我没有参加比赛，所以下载不了

目前的数据你可以自己划分训练集、验证集和测试集或者使用其它数据，先做实验。稍后我通过百度网盘来分享数据。

**Comment by ZTurboX** [comment]
非常感谢
