### ISSUE TITLE
关于效果和联合训练

### ISSUE THREAD

**Issue by liutianling** [yuanxiaosc/Entity-Relation-Extraction#11]
不知道您这种管道式的训练效果如何呢？
另外，基于bert的高准确率，在构建损失函数的时候，直接组合两个任务的损失，也就是分类损失和标注损失的和，然后做fine-tunning？您这种方法可行吗？
有看到有人做联合训练的，好像目前效果都还不够。
谢谢！

**Comment by yuanxiaosc** [comment]
@liutianling 管道式模型效果见文末，联合模型见文末。
