### ISSUE TITLE
请问一下，这个模型和Multiple-Relations-Extraction-Only-Look-Once这个模型的算法有什么区别吗？

### ISSUE THREAD

**Issue by eece-23** [yuanxiaosc/Entity-Relation-Extraction#12]
请问一下，这个模型和Multiple-Relations-Extraction-Only-Look-Once这个模型的算法有什么区别吗？还有就是结果哪个好一些

**Comment by zhaizhijiang** [comment]
请问Multiple-Relations-Extraction-Only-Look-Once这个您实现了吗？

**Comment by yuanxiaosc** [comment]
@snowzjy  这个资源是管道式处理，先抽关系在抽关系对应的实体。Multiple-Relations-Extraction-Only-Look-Once是端到端模型，一次性同时抽取关系和实体。

**Comment by snowzjy** [comment]
@yuanxiaosc 问一下，这个算法如果要用远程监督啥的，是不是还要另外写代码？有没有现成的框架可以用？

**Comment by yuanxiaosc** [comment]
https://blog.csdn.net/yywang_hit/article/details/79705099
有关远程监督，我的理解是与模型无关，可以算作一种通用的数据增强手段。我没有使用过这个技术，你可以自行找资料。

snowzjy <notifications@github.com> 于 2019年7月18日周四 下午3:30写道：
