### ISSUE TITLE
完成了关系和序列标注模型训练后模型的使用问题

### ISSUE THREAD

**Issue by cronousbaby** [yuanxiaosc/Entity-Relation-Extraction#14]
您好，我按照您的代码和思路完成了关系分类模型和实体识别模型的训练，如果进行模型的使用呢，比如 我input：句子1   调用模型后 输出了 实体和相关关系的信息表

**Comment by yuanxiaosc** [comment]
@cronousbaby 直接执行模型预测阶段即可，和训练阶段一样，分为关系预测和实体预测两个阶段，最后执行python produce_submit_json_file.py来整理输出最终的实体以及对应的关系。需要注意的是模型的输入和输出都是一个batch，如果只有一个句子的话可以把batchsize设置为1。

**Comment by cronousbaby** [comment]
非常感谢您的回答，关注您的文章很久了，昨天我用GPU进行了模型训练 发现 您代码中设置的批次是32  由于训练出现了OOM 所以我设置为了16。
关系分类模型和实体识别模型耗时大概1天左右的时间，一会回去看一下



------------------ 原始邮件 ------------------
发件人: "Little star"<notifications@github.com>;
发送时间: 2019年7月22日(星期一) 下午4:01
收件人: "yuanxiaosc/Entity-Relation-Extraction"<Entity-Relation-Extraction@noreply.github.com>;
抄送: "蘑菇小象"<626827378@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [yuanxiaosc/Entity-Relation-Extraction] 完成了关系和序列标注模型训练后模型的使用问题 (#14)




@cronousbaby 直接执行模型预测阶段即可，和训练阶段一样，分为关系预测和实体预测两个阶段，最后执行python produce_submit_json_file.py来整理输出最终的实体以及对应的关系。需要注意的是模型的输入和输出都是一个batch，如果只有一个句子的话可以把batchsize设置为1。
