### ISSUE TITLE
请问作者，在预测对应实体的部分的问题

### ISSUE THREAD

**Issue by weikang-wang** [yuanxiaosc/Entity-Relation-Extraction#15]
在预测实体部分，我发现您好像并没有使用关系的信息，只是采用了联合训练的方式，是这样的吗？

**Comment by yuanxiaosc** [comment]
@weikang-wang 仔细看模型预测部分，模型预测了实体以及关系

**Comment by weikang-wang** [comment]
> @weikang-wang 仔细看模型预测部分，模型预测了实体以及关系

额，我之前表达不太对，我是说训练序列标注模型的时候，并没有把关系信息与序列标注部分进行融合，只是采用联合训练的方式来辅助序列标注实体。

**Comment by yuanxiaosc** [comment]
@weikang-wang 说明之中解释了该资源的原理“该代码以管道式的方式处理实体及关系抽取任务，首先使用一个多标签分类模型判断句子的关系种类，然后把句子和可能的关系种类输入序列标注模型中，序列标注模型标注出句子中的实体，最终结合预测的关系和实体输出实体-关系列表：（实体1，关系，实体2）。”
也就是说在做实体预测时候，模型的输入是句子以及上一阶段关系预测模型预测出的关系，不知道这算不算一种融合。
