### ISSUE TITLE
你好，请教一下，这个模型的结果能排到第几呢

### ISSUE THREAD

**Issue by dh12306** [yuanxiaosc/Entity-Relation-Extraction#17]
rt，谢谢 @yuanxiaosc

**Comment by yuanxiaosc** [comment]
请把README看完再来问这样的问题

**Comment by SunnyMarkLiu** [comment]
README中并没有提到第几名，，，README中贴的是冠军团队的PPT，我是在 `2019语言与智能技术竞赛信息抽取排行榜.png` 中看到的43。
