### ISSUE TITLE
模型预测的输入格式

### ISSUE THREAD

**Issue by liutianling** [yuanxiaosc/Entity-Relation-Extraction#18]
您好，这个模型的输入是什么，两个实体和他们的词性，以及整个句子？

**Comment by yuanxiaosc** [comment]
@liutianling 该代码以管道式的方式处理实体及关系抽取任务，首先使用一个多标签分类模型判断句子的关系种类，然后把句子和可能的关系种类输入序列标注模型中，序列标注模型标注出句子中的实体，最终结合预测的关系和实体输出实体-关系列表：（实体1，关系，实体2）。

第一个模型输入是句子（没有利用词性信息），输出是可能的关系。第二个模型输入是句子和可能的关系，输出是序列标签（实体信息）。结合这两个模型的输出就可以得到实体关系三元组。
