### ISSUE TITLE
思想原论文

### ISSUE THREAD

**Issue by 1234560o** [yuanxiaosc/Entity-Relation-Extraction#21]
作者，您好！先进行关系分类再识别实体这种思想有相关论文提供吗？

**Comment by yuanxiaosc** [comment]
@1234560o  这种流程我不清楚最早来自那篇论文，是参照笔试官方给的baseline写的这个流程。也比较容易理解，如果先抽实体再抽关系的话会导致不知道实体与关系的对应关系，当然也可以同时抽取。
