### ISSUE TITLE
没有找到生成token_in.txt等txt文件的代码？

### ISSUE THREAD

**Issue by lijunforNLPtraining** [yuanxiaosc/Entity-Relation-Extraction#23]
token_in.txt，predicate_out.txt等txt文件是在哪里生成的呢，我看第一个issue也是问的这个问题，下载训练数据是没有问题，但是很明显txt文件没有啊，请问博主可以提供该文件和文件的生成脚本吗？感谢

**Comment by yuanxiaosc** [comment]
@lijunforNLPtraining 在readme文件很明显的地方有如下内容“准备关系分类数据
python bin/predicate_classifiction/predicate_data_manager.py”
