### ISSUE TITLE
准确率问题：用了跟您一样的数据，准确率只有百分之五十多

### ISSUE THREAD

**Issue by strawberrylunar** [yuanxiaosc/Entity-Relation-Extraction#24]
具体截图如下：准确率和召回率
![KF4DANL%ENNFYUDZMZU6B(I](https://user-images.githubusercontent.com/39673281/67156599-3d6e8880-f353-11e9-8a5e-0f677992059a.png)
precision:0.5743
recall:0.5948
F1-score:0.5844

实体关系分类的完全准确率和部分准确率：
![MYG8()08L%GQLGV9L_ZGI(T](https://user-images.githubusercontent.com/39673281/67156934-81fc2300-f357-11e9-96b5-622692704466.png)
图片上传失败，内容如下：

correct_line: 509, line: 1000, percentage: 50.9000%

superset_line: 141, line: 1000, percentage: 14.1000%

subset_line: 254, line: 1000, percentage: 25.4000%

没有想到原因，望指教！

**Comment by yuanxiaosc** [comment]
@strawberrylunar 模型效果跟训练的周期数有关系，你可以通过查看模型损失或者准确率是否收敛来判断是否停止训练。如readme文件所写：在分类模型epochs6ckpt20000和序列标注模型epochs9ckpt17000时的准确率召回率F1值分别是 0.8651 | 0.738 | 0.7965

**Comment by strawberrylunar** [comment]
谢谢！我已经增加了训练轮次，目前模型正在训练中。再次感谢！




------------------ 原始邮件 ------------------
发件人: "TF-KMP"<notifications@github.com>; 
发送时间: 2019年10月21日(星期一) 晚上10:55
收件人: "yuanxiaosc/Entity-Relation-Extraction"<Entity-Relation-Extraction@noreply.github.com>; 
抄送: "张琪"<504692797@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [yuanxiaosc/Entity-Relation-Extraction] 准确率问题：用了跟您一样的数据，准确率只有百分之五十多 (#24)




@strawberrylunar 模型效果跟训练的周期数有关系，你可以通过查看模型损失或者准确率是否收敛来判断是否停止训练。如readme文件所写：在分类模型epochs6ckpt20000和序列标注模型epochs9ckpt17000时的准确率召回率F1值分别是 0.8651 | 0.738 | 0.7965
