### ISSUE TITLE
关于关系抽取的问题

### ISSUE THREAD

**Issue by ididhmc** [yuanxiaosc/Entity-Relation-Extraction#25]
您好，阅读了您的代码，主要有两个问题不太理解，想咨询一下您
1.   分类模型在modeling的训练模型最终的结果是batch_size*128*768,128代表的是句长，为什么最后只取第一个字作为分类的标准？后面的字都不需要了吗？
![image](https://user-images.githubusercontent.com/41049893/67541970-6f9a3480-f71d-11e9-89b3-6ee6ac471142.png)
2.    在关系抽取模型里，我看到代码是分别预测标签和文本的BIO分别训练，也就是说预测标签结果不依赖于文本的BIO
![image](https://user-images.githubusercontent.com/41049893/67542017-a2442d00-f71d-11e9-82a1-ebea2885e279.png)
![image](https://user-images.githubusercontent.com/41049893/67542082-e0415100-f71d-11e9-93db-9b68c209baca.png)
  但是一般不是先给文本打上BIO标签以后，再和BIO标签一起去训练文本得到预测标签吗？

**Comment by yuanxiaosc** [comment]
@ididhmc 
1. 取第一个是因为根据BERT论文中的描述，第一个token的信息就可以代表整句话的内容。当然你可以用池化整句话的信息或者LSTM处理后的最终内容来代表整句话的内容。
2. 序列标注模型依赖于BIO标注信息，可以查看模型的输入数据 ![](https://img-blog.csdnimg.cn/20190730165604209.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80MjAwMTA4OQ==,size_16,color_FFFFFF,t_70)

最建议你的就是仔细阅读readme文件中提及的： bert实践:关系抽取解读 https://blog.csdn.net/weixin_42001089/article/details/97657149
