### ISSUE TITLE
请问postag embedding是怎么做的？

### ISSUE THREAD

**Issue by broccolik** [yuanxiaosc/Entity-Relation-Extraction#27]
请问 postag embedding 部分是对每个字或者每个词对应的postag进行embedding吗？比如{"word": "的", "pos": "u"}  是对“u”进行embedding吗？

**Comment by yuanxiaosc** [comment]
@broccolik 这里没有用到postag的信息，如果要有也最好用基于字的postag ，因为BERT中文预训练模型的参数都是基于字训练的。

**Comment by broccolik** [comment]
谢谢，你们的报告里面基础模型有说用到字的postag和词的postag，现在这两块都没有实际用到是吗？

**Comment by broccolik** [comment]
谢谢，你们的报告里面基础模型有说用到字的postag和词的postag，现在这两块都没有实际用到是吗？
