### ISSUE TITLE
作者你好，代码运行出错

### ISSUE THREAD

**Issue by cbigeyes** [yuanxiaosc/Entity-Relation-Extraction#3]
sequence_labeling_data_manager.py是否没有添加对test数据的处理。
我没有找到能够运行run_sequence_labeling.py的test数据集，也就是不能找到test/token_in_and_one_predicate.txt文件，是我忽略了某些操作吗，谢谢

**Comment by yuanxiaosc** [comment]
已经更新了文件结构，跑了一遍代码，应该没有大的问题了

**Comment by cbigeyes** [comment]
> 已经更新了文件结构，跑了一遍代码，应该没有大的问题了

好的，谢谢～
