### ISSUE TITLE
生成实体-关系结果过程中出现问题

### ISSUE THREAD

**Issue by zuoxy1997** [yuanxiaosc/Entity-Relation-Extraction#30]
在运行python produce_submit_json_file.py时候，

# python produce_submit_json_file.py
Traceback (most recent call last):
  File "produce_submit_json_file.py", line 324, in <module>
    spo_list_manager = Sorted_relation_and_entity_list_Management(TEST_DATA_DIR, MODEL_OUTPUT_DIR, Competition_Mode=Competition_Mode)
  File "produce_submit_json_file.py", line 133, in __init__
    File_Management.__init__(self, TEST_DATA_DIR=TEST_DATA_DIR, MODEL_OUTPUT_DIR=MODEL_OUTPUT_DIR, Competition_Mode=Competition_Mode)
  File "produce_submit_json_file.py", line 82, in __init__
    self.MODEL_OUTPUT_DIR = get_latest_model_predict_data_dir(MODEL_OUTPUT_DIR)
  File "produce_submit_json_file.py", line 22, in get_latest_model_predict_data_dir
    if not os.path.exists(new_ckpt_dir):
UnboundLocalError: local variable 'new_ckpt_dir' referenced before assignment

出现 local variable 'new_ckpt_dir' referenced before assignment

**Comment by yuanxiaosc** [comment]
@zuoxy1997 这里程序已经指出了错误，new_ckpt_dir 变量没有赋值就被使用，可以查到该变量属于get_latest_model_predict_data_dir 函数，该函数是为了获取模型输出文件的路径，若没有正常工作，你可以直接手动指定MODEL_OUTPUT_DIR参数的值。
