### ISSUE TITLE
运行出错报keyError的问题

### ISSUE THREAD

**Issue by XinXinShawn** [yuanxiaosc/Entity-Relation-Extraction#31]
def _predicate_label_to_id(predicate_label, predicate_label_map): 函数是把关系标签转换成onehot向量，关系全部定义在    def get_labels(self):中，只要是这里面的关系都可以转换，所以你可以输出一下这个key，即predicate_label_map[label] 中的label看看

_Originally posted by @yuanxiaosc in https://github.com/yuanxiaosc/Entity-Relation-Extraction/issues/4#issuecomment-483506103_
作者你好，我在训练关系分类模型时也出现keyError。将label print出来后发现label为空，原语料中这一句话确实是没有关系类别。请问该怎么解决的？

**Comment by yuanxiaosc** [comment]
@XinXinShawn  该模型假定了每句输入的语料都含有至少一个预定义的49种关系，所以如果原语料某些句子没有关系，建议直接删除。当然你可以再训练一个二分类模型来判断某句话是否含有关系。
