### ISSUE TITLE
run_sequence_labeling评测错误

### ISSUE THREAD

**Issue by broccolik** [yuanxiaosc/Entity-Relation-Extraction#35]
您好，请问您在run_sequence_labeling做评测时有报下面这个错误吗？
TypeError: Values of eval_metric_ops must be (metric_value, update_op) tuples, given: Tensor("ArgMax:0", shape=(?,), dtype=int32) for key: predicate_prediction

**Comment by yuanxiaosc** [comment]
@broccolik 不用TensorFlow的代码来评测模型效果（--do_eval=false ），直接使用 Entity-Relation-Extraction/bin/evaluation/ 下面的代码即可
