### ISSUE TITLE
epochs6ckpt1000这个模型是指的，第6个epochs的第1000次迭代的模型吗？

### ISSUE THREAD

**Issue by tanzf** [yuanxiaosc/Entity-Relation-Extraction#37]
epochs6ckpt1000这个模型是指的，第6个epochs的第1000次迭代的模型吗？

**Comment by yuanxiaosc** [comment]
@tanzf 你的理解是对的ckpt1000就指模型迭代了1000次，epochs6是指最大训练6个周期，所以还可能出现epochs6ckpt2000，epochs6ckpt3000
