### ISSUE TITLE
关于处理和实体类型确认的问题

### ISSUE THREAD

**Issue by Ludong418** [yuanxiaosc/Entity-Relation-Extraction#41]
您好，感谢您提供的代码，本人学习您的代码过程中，有两个疑惑：
1. 您在前期处理bert tokenizer 产生##字符串时候，做了[##WordPiece]替换，这一步的目的我不太理解，我本人觉得应该是可以省略此步骤，因为这样可以减少第二个模型的类型，且在预测结果也方便了处理。
2. 是否对于一种关系有多种实体类型情况，是否就无法确定两实体到底属于这关系下的那个实体类型了

**Comment by yuanxiaosc** [comment]
你的第二个问题正中要害，produce_submit_json_file.py 中使用了最大匹配的方法，即把所有可能的实体进行配对，你可以改写其中的函数来获得更好的效果。第一个问题无关紧要，不影响结果。
