### ISSUE TITLE
您这个模型，想要达到第一名的准确率，还需要做些什么工作？

### ISSUE THREAD

**Issue by hqsh** [yuanxiaosc/Entity-Relation-Extraction#46]
非常感谢您的分享，想讨教一下，您这个模型，想要达到第一名的准确率，还需要做些什么工作，或者已有更高准确率的方案能否分享一下？谢谢！

**Comment by yuanxiaosc** [comment]
@hqsh 至少有三个方向工作的可以做：1）从数据入手。可以对已有的数据进行纠错和提取先验知识，进一步挖掘数据集内部的常识。2）从模型入手。比如改变模型的输入，利用数据集标注的词性信息。还可以改变损失函数等等。3）利用一些技巧。具体可以参见Schema约束的知识抽取系统架构（“信息抽取”任务冠军队伍报告）.pdf

**Comment by hqsh** [comment]
感谢解答！
您提到的 “利用数据集标注的词性信息”，看 raw_data 下面的文件，以及冠军队伍的 pdf，看上去是 jieba 标记的词性。之前也确实听说过百度的 NLP，喜欢用中文词组，而不是一个个独立的字。但实际操作中，我从没这么弄过，不确定 BERT 是否能支持、如何操作才能支持 “利用数据集标注的词性信息” ？谢谢！
