### ISSUE TITLE
raw_data 里面的数据是否不全，官方已经停止下载数据了，能否共享一下全量数据？感谢！

### ISSUE THREAD

**Issue by hqsh** [yuanxiaosc/Entity-Relation-Extraction#47]
看到 readme.md 里面有提到：“本次竞赛使用的SKE数据集是业界规模最大的基于schema的中文信息抽取数据集，其包含超过43万三元组数据、21万中文句子”，实际看 raw_data 里面只有几千句话。

官方已经停止下载数据了，能否共享一下全量数据？

感谢！

**Comment by yuanxiaosc** [comment]
https://drive.google.com/open?id=1O1j4UMqCf23-peOth_GpcKLY85duPPmQ

Good luck

**Comment by rersister** [comment]
打扰了，我也想要下全部数据，但是上面的链接我已经无法打开了，可以再共享下吗？麻烦了

**Comment by hqsh** [comment]
链接: https://pan.baidu.com/s/1vNIe1pR63KWnawtITLqCvw 提取码: 6rjm


不用谢啦，麻烦抽空加心，找工作用。
https://github.com/hqsh










 原始邮件 
发件人: resister<notifications@github.com>
收件人: yuanxiaosc/Entity-Relation-Extraction<Entity-Relation-Extraction@noreply.github.com>
抄送: hqsh<hqsh@live.cn>; Author<author@noreply.github.com>
发送时间: 2020年7月14日(周二) 22:15
主题: Re: [yuanxiaosc/Entity-Relation-Extraction] raw_data 里面的数据是否不全，官方已经停止下载数据了，能否共享一下全量数据？感谢！ (#47)


打扰了，我也想要下全部数据，但是上面的链接我已经无法打开了，可以再共享下吗？麻烦了

**Comment by rersister** [comment]
我链接下载的和在你项目github地址下载的数据量对比了下是一样的，全数据量就是在raw_data里面了，是吗？

**Comment by hqsh** [comment]
不清楚，百度网盘上面就是 google driver 上面的全量数据。






 原始邮件 
发件人: resister<notifications@github.com>
收件人: yuanxiaosc/Entity-Relation-Extraction<Entity-Relation-Extraction@noreply.github.com>
抄送: hqsh<hqsh@live.cn>; Author<author@noreply.github.com>
发送时间: 2020年7月15日(周三) 09:56
主题: Re: [yuanxiaosc/Entity-Relation-Extraction] raw_data 里面的数据是否不全，官方已经停止下载数据了，能否共享一下全量数据？感谢！ (#47)


我链接下载的和在你项目github地址下载的数据量对比了下是一样的，全数据量就是在raw_data里面了，是吗？
