### ISSUE TITLE
关于预测效果询问

### ISSUE THREAD

**Issue by pergrand** [yuanxiaosc/Entity-Relation-Extraction#49]
大神你好，按照这个代码运行，关系分类 6轮，序列标注9轮，训练出了来预测结果f1只有0.67.请问是哪里的问题。在自己的数据上训练的。数据量差不多，关系分类有60多种。也用了官方数据训练，f1也不到0.7.请问是哪里有问题吗。

**Comment by yuanxiaosc** [comment]
@pergrand 影响F1值的因素有很多，特别是模型和数据，但是可以先看看模型的分别在训练集和验证集的准确率和召回率情况。下面仅仅举例，具体分析可以百度调参技巧。如果在训练集准确率/召回率低那么，说明模型容量不够或模型训练周期不够。如果在训练集效果好，但是在验证集效果差，则要考虑模型是否过拟合了，则要减少模型训练周期。还有需要在准确率和召回率之间权衡。

由于这个模型是两阶段的模型，所以效果会受到两个阶段模型的综合影响，比如即使每个模型的准确率都达到了90%，两个阶段的最终效果也只有90%*90%=81%，所以模型效果上限不会太高，理论上限是在95%*95%=90.25%（第一名的效果89.75%已经是很高的了）。

要提升效果最简单的办法就是使用更强的模型或更多的数据，所以建议你直接使用预训练语言模型库HuggingFace-Transformers里面的模型，使用起来很简单，可以参考我的博文https://yuanxiaosc.github.io/2019/12/30/HuggingFace-Transformers%E6%89%8B%E5%86%8C/

**Comment by pergrand** [comment]
> @pergrand 影响F1值的因素有很多，特别是模型和数据，但是可以先看看模型的分别在训练集和验证集的准确率和召回率情况。下面仅仅举例，具体分析可以百度调参技巧。如果在训练集准确率/召回率低那么，说明模型容量不够或模型训练周期不够。如果在训练集效果好，但是在验证集效果差，则要考虑模型是否过拟合了，则要减少模型训练周期。还有需要在准确率和召回率之间权衡。
> 
> 由于这个模型是两阶段的模型，所以效果会受到两个阶段模型的综合影响，比如即使每个模型的准确率都达到了90%，两个阶段的最终效果也只有90%*90%=81%，所以模型效果上限不会太高，理论上限是在95%*95%=90.25%（第一名的效果89.75%已经是很高的了）。
> 
> 要提升效果最简单的办法就是使用更强的模型或更多的数据，所以建议你直接使用预训练语言模型库HuggingFace-Transformers里面的模型，使用起来很简单，可以参考我的博文https://yuanxiaosc.github.io/2019/12/30/HuggingFace-Transformers%E6%89%8B%E5%86%8C/

在您的解决方案里是使用了bert预训练模型；不是和HuggingFace-Transformers使用预训练模型一样吗？与您建议使用这个里面的预训练模型应该没有多大区别吧，调整模型的话应该是在下游分类模型上调整吧。博主，我看您去年的那个比赛里官方F1值是0.8左右，是直接使用该代码训练预测的吗；

**Comment by yuanxiaosc** [comment]
我去年参加比赛的是这个代码和模型
