### ISSUE TITLE
作者您好，最后结果recall极低请问是什么问题

### ISSUE THREAD

**Issue by mymxhdd** [yuanxiaosc/Entity-Relation-Extraction#5]

**Comment by yuanxiaosc** [comment]
@mymxhdd 请问你得出的召回率具体是多少？我已经在README.md文件末尾中给了参考数值，稍微训练（train step=20000左右）召回率可以达到70左右。在本月下旬我会更新代码F1值应该可以达到83+

**Comment by wangbq18** [comment]
> 
> 
> @mymxhdd 请问你得出的召回率具体是多少？我已经在README.md文件末尾中给了参考数值，稍微训练（train step=20000左右）召回率可以达到70左右。在本月下旬我会更新代码F1值应该可以达到83+
请问您用BERT做joint实体关系抽取F1能达到多少

**Comment by wangbq18** [comment]
@yuanxiaosc  请问您用BERT做joint实体关系抽取F1能达到多少

**Comment by yuanxiaosc** [comment]
这份代码目前可以达到F1=80左右，联合模型那份代码(通过手模板处理输出结果)可以达到83

**Comment by wangbq18** [comment]
> 
> 
> 这份代码目前可以达到F1=80左右，联合模型那份代码(通过手模板处理输出结果)可以达到83

厉害，不过您说的手模板处理指的是什么？

**Comment by wangbq18** [comment]
> 
> 
> 这份代码目前可以达到F1=80左右，联合模型那份代码(通过手模板处理输出结果)可以达到83

@yuanxiaosc 厉害，不过您说的手模板处理指的是什么？

**Comment by yuanxiaosc** [comment]
@wangbq18 https://github.com/yuanxiaosc/Schema-based-Knowledge-Extraction 下面bin里面的内容就是结合了模板和神经网络预测生成最终结果的代码。模板是根据这个数据集的统计信息和特征写的针对这个数据集的代码，可以进一步提升效果。

**Comment by wangbq18** [comment]
> 
> 
> @wangbq18 https://github.com/yuanxiaosc/Schema-based-Knowledge-Extraction 下面bin里面的内容就是结合了模板和神经网络预测生成最终结果的代码。模板是根据这个数据集的统计信息和特征写的针对这个数据集的代码，可以进一步提升效果。

@yuanxiaosc got it! 棒！

**Comment by mymxhdd** [comment]
@yuanxiaosc 我的trainstep也达到了20000+但是在dev上验证的f1值只有70

**Comment by yuanxiaosc** [comment]
> @yuanxiaosc 我的trainstep也达到了20000+但是在dev上验证的f1值只有70

这是有可能的，我那个README.md 文件那个F1值是官方在验证集上的结果接近80。在验证集上我没详细实验。目前有一个问题是这份代码急需解决的，就是输入的答案含有空格，那么模型输出结果一定是错误的（比如英文人名）。因为模型输入数据是用空格分隔的，所以可以先把数据中的空格用特殊符号替换，再把结果中的特殊符号换成空格。这样可以提升不少分数。
