### ISSUE TITLE
一句话中同一种关系出现多次

### ISSUE THREAD

**Issue by Jason-kid** [yuanxiaosc/Entity-Relation-Extraction#51]
比如在一句话中，“张三的国籍是中国，李四的国籍是印度”，出现两次“国籍”这个关系需要预测，那么在关系分类模型中，对应label是国籍，还是国籍，国籍呢？

**Comment by wangkangdegithub** [comment]
是啊 被这种问题困扰住了。坐等解答

**Comment by wangkangdegithub** [comment]
个人理解一句话中同一种关系出现多次时，在关系分类模型里出现的应该还是一个label，也就是在做关系抽取时一句话的一类关系只能抽出一个三元组。但如果要抽出多个三元组该怎么解决？有没有好的思路？

**Comment by YaleFeng** [comment]
同问
