### ISSUE TITLE
请问博主，在第一步预测出关系种类后，第二部识别实体任务中，使用到的是第一步预测到的关系数量，还是使用的是具体的关系类型

### ISSUE THREAD

**Issue by wangcxcup** [yuanxiaosc/Entity-Relation-Extraction#56]
请问博主，在第一步预测出关系种类后，第二部识别实体任务中，使用到的是第一步预测到的关系数量，还是使用的是具体的关系类型，比如一句话在第一步中预测出0，1，2三种关系，在第二步中是否还需要再次预测关系的类型（即是否关系类型和标识实体同时进行），还是说第二步是在已知第一步的关系类型的的情况下，仅需要去标识实体就可以了？

**Comment by yuanxiaosc** [comment]
@wangcxcup 使用第一步预测出来的关系类型
