### ISSUE TITLE
有关原始数据格式问题

### ISSUE THREAD

**Issue by BIGPIMPIMP** [yuanxiaosc/Entity-Relation-Extraction#57]
作者，很感谢您分享的模型，有一点疑惑，在raw data中，训练数据和测试数据里都带有POS信息，这应该比赛官方给的吧？这就相当于提前给大家做了分词和词性标注工作，请问这是赛会有意为之？BERT作为NLP上游任务的预训练模型，可以实现分词和词性标注工作，那请问您这套代码里是直接使用数据集里自带的分词和词性标注结果吗？
如果我想在自己的数据集上做测试，是否意味着也需要提前准备好同一标准的POS标注信息？

**Comment by yuanxiaosc** [comment]
可以利用POS信息作为补充信息，仅仅是可选而已，具体效果如何需要实验验证。这套代码没有使用词性标注结果。在自己数据集上做实验也不需要一套标准的POS信息

**Comment by youyanjiangcuca** [comment]
是不是训练自己的数据可以不用标注词性,只标注三元组结果

**Comment by yuanxiaosc** [comment]
> 是不是训练自己的数据可以不用标注词性,只标注三元组结果

理解是对的
