### ISSUE TITLE
关于第二步标注模型的几个问题以及改进办法的讨论

### ISSUE THREAD

**Issue by oushu1zhangxiangxuan1** [yuanxiaosc/Entity-Relation-Extraction#58]
## 1. 关于输入，
是否可以在第二个segment中只输入单个的关系label值，
而不是要求输入和第一个segment等长的重复label，
因为这样会限制原生字符串的长度小于(max_seq_lenght-3)/2

但是不知道只使用单个label会不会影响模型的性能

## 2. 关于输出， 
由于predicate已经作为输入， 
此时再将predicate作为预测目标是不是有点多余，
而且multi-optimal 类型的task的loss很难权衡(源码中将predicate_loss 的权重hard code为0.5)
可否直接取消predicate_loss，转换为label_loss单目标优化任务

## 3. 加入crf层
在2的基础上加上crf，感觉可以提示一些效果

目前源码的解决方案在百度给的2019数据集上表现还挺不错的👍，
对于上面两个问题希望能和作者深入讨论一下，
有时间的话我准备根据1、2进行改动验证一下
另外请问一下repo主有没有百度2020比赛的数据集，有的话跪求发一份😂  
邮箱： johnsaxon@foxmail.com
多谢！

**Comment by yuanxiaosc** [comment]
1. 需要实验来看。2. 再将predicate作为预测目标仅仅是凭个人感觉加的，可以去掉。取0.5也是凭感觉取的，在没有更多信息的情况下，我一般取个平均数。3. 有很多在BERT上面加CRF层的实验，少数实验有效果，大部分不仅增加了训练和预测时间还几乎没效果。4. 目前我已经在百度工作了，不能再分享百度的数据集了。你想要数据的话最好通过参赛的方式获取。

**Comment by oushu1zhangxiangxuan1** [comment]
> 1. 需要实验来看。2. 再将predicate作为预测目标仅仅是凭个人感觉加的，可以去掉。取0.5也是凭感觉取的，在没有更多信息的情况下，我一般取个平均数。3. 有很多在BERT上面加CRF层的实验，少数实验有效果，大部分不仅增加了训练和预测时间还几乎没效果。4. 目前我已经在百度工作了，不能再分享百度的数据集了。你想要数据的话最好通过参赛的方式获取。

多谢！

针对1、2做了ablation
相同epochs下
1会严重降低模型各项指标
2会提升recall但precision会下降，f1-score会有0.1的提升，总体来讲没啥效果
1、2同时用效果在单独使用1、2的效果之间，但比1效果好很多

**Comment by yuanxiaosc** [comment]
@oushu1zhangxiangxuan1 看来你是一个行动派了，这么快就出了结果。再深入分析下导致模型性能变化的原因，可以发论文滴。我以前读研期间只知道出了效果更好的模型能发论文，不知道做分析的论文也能发。

**Comment by oushu1zhangxiangxuan1** [comment]
> @oushu1zhangxiangxuan1 看来你是一个行动派了，这么快就出了结果。再深入分析下导致模型性能变化的原因，可以发论文滴。我以前读研期间只知道出了效果更好的模型能发论文，不知道做分析的论文也能发。

哈哈，前一段调研完就被薅去搞别的了，等以后有空了好好研究一下，大神repo的这个方案是比较靠谱的👍
