### ISSUE TITLE
P、R和F1值输出在哪里？怎么没找到？

### ISSUE THREAD

**Issue by wusaisa** [yuanxiaosc/Entity-Relation-Extraction#59]
请问下运行完python bin/evaluation/evaluate_classifiction.py和python bin/evaluation/evaluate_labeling.py之后，P、R和F1值输出在哪里？怎么没找到呢？谢谢啦，非常急需，希望得到回复~

**Comment by yuanxiaosc** [comment]
@wusaisa 直接打印输出了啊，就是简单的计数而已，你可以自己稍微修改代码或者自己写
