### ISSUE TITLE
作者您好，请问用cpu训练需要多长时间？

### ISSUE THREAD

**Issue by yjxxin** [yuanxiaosc/Entity-Relation-Extraction#6]

**Comment by wangbq18** [comment]
cpu就算了吧

**Comment by yuanxiaosc** [comment]
我也是用CPU训练的，同时训练分类模型和序列标注模型的话大概3天左右可用，我是在32核心的机器上训练的。

**Comment by yjxxin** [comment]
作者您好           
 if file_set_type == "train":
                path_to_raw_data_file = "train_data.json"
            elif file_set_type == "valid":
                path_to_raw_data_file = "dev_data.json"
            else:
                pass
在run_sequnce_labeling.py里是不是没有对test文件的操作
我运行后没有找到这个文件 
'bin/subject_object_labeling/sequence_labeling_data/test/token_in_and_one_predicate.txt'
