### ISSUE TITLE
如何输出最佳模型？

### ISSUE THREAD

**Issue by Gavingx** [yuanxiaosc/Entity-Relation-Extraction#61]
bert里面estimator都是封装好的高级API，只能等所有的epochs都跑完之后才会跑验证集，这样根本没法知道保存的哪个ckpt是在验证集上表现最佳的，请问如何在每保存一个ckpt之后验证一次？  或者作者是怎么测试的，能分享一下吗？ 谢谢！

**Comment by yuanxiaosc** [comment]
> bert里面estimator都是封装好的高级API，只能等所有的epochs都跑完之后才会跑验证集，这样根本没法知道保存的哪个ckpt是在验证集上表现最佳的，请问如何在每保存一个ckpt之后验证一次？ 或者作者是怎么测试的，能分享一下吗？ 谢谢！

我的经验是，当训练结果还不稳定时直接看训练过程中的表现即可（在测试集的准确率、auc等等），等到效果稳定时，再加载模型用测试模式。至于你说的问题可以通过设置训练epoch数量，或者另外加载模型（最新的ckpt文件）跑测试集
