### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by hongdangshao** [yuanxiaosc/Entity-Relation-Extraction#62]
Hi:
    Excuse me.I have a question of the run_sequence_labeling.py. In this script, tokens_b = [text_predicate] * len(text_token),why you let text_predicate multiply the length of text_token list?In my view,I think it should be multiplied by 1.

**Comment by yuanxiaosc** [comment]
@hongdangshao 原来的构造是没有问题的。其实tokens_b部分不是必须的，关键记住这里是一个序列标注任务，保证输入个数与预测个数对齐即可（体现在input_ids与token_label_ids中id个数和位置对应），你可以尝试其它构造方式都是可以的。

**Comment by hongdangshao** [comment]
> @hongdangshao 原来的构造是没有问题的。其实tokens_b部分不是必须的，关键记住这里是一个序列标注任务，保证输入个数与预测个数对齐即可（体现在input_ids与token_label_ids中id个数和位置对应），你可以尝试其它构造方式都是可以的。
非常感谢您的回复！发现您这样做有道理的。保证了text_token与token_b长度一致，且能对应到相应的predicate种类。一枚正在学习信息提取小白，希望有问题能多多向您请教！果然打中文方便多了。哈哈哈~
