### ISSUE TITLE
复现准确率差几个百分点

### ISSUE THREAD

**Issue by YYGe01** [yuanxiaosc/Entity-Relation-Extraction#64]
作者您好，感谢开源！

我复现的结果，在验证集上F1是0.76，请问这个合理吗，我看您有0.79，请问是差了哪个地方呢？谢谢！

另外我看官网评估时使用了百度知识图谱别名字典，请问下我准确率差一点的原因是否是少了这个字典呢？不知道作者能否提供这个字典？谢谢！

**Comment by yuanxiaosc** [comment]
一般来说使用默认的配置，F1值差距应该在万分位，这里差距在百分位应该是不合理的。可以修改produce_submit_json_file.py产生更合理的结果。
