### ISSUE TITLE
预测问题

### ISSUE THREAD

**Issue by 1120161807** [yuanxiaosc/Entity-Relation-Extraction#66]
您好！非常感谢您的代码，学习了！想请问一下您，如果我想输入句子测试的话，一定要先人工对其切分处理成{'word' : 'xxx'}的格式吗？

**Comment by Xie-Minghui** [comment]
你好！请问你还有SKE数据集，官网已经无法下载了

**Comment by yuanxiaosc** [comment]
> 您好！非常感谢您的代码，学习了！想请问一下您，如果我想输入句子测试的话，一定要先人工对其切分处理成{'word' : 'xxx'}的格式吗？

处理成模型可以接受的id形式即可，不受限于该格式

**Comment by 1120161807** [comment]
感谢您的回复！我刚才又看了一下处理数据的地方，发现只用到了json中的"spo_list"和"text"内容，所以即使我输入的就是一个句子也能正常预测运行，是这样理解吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuanxiaosc/Entity-Relation-Extraction"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月2日(星期二) 晚上9:42
收件人:&nbsp;"yuanxiaosc/Entity-Relation-Extraction"<Entity-Relation-Extraction@noreply.github.com&gt;;
抄送:&nbsp;"v"<86456858@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yuanxiaosc/Entity-Relation-Extraction] 预测问题 (#66)





  
您好！非常感谢您的代码，学习了！想请问一下您，如果我想输入句子测试的话，一定要先人工对其切分处理成{'word' : 'xxx'}的格式吗？
  
处理成模型可以接受的id形式即可，不受限于该格式
