### ISSUE TITLE
老哥，为啥run_sequence_labeling还需要计算predicate loss

### ISSUE THREAD

**Issue by cbigeyes** [yuanxiaosc/Entity-Relation-Extraction#7]
如题，为啥run_sequence_labeling还需要计算predicate loss

**Comment by yuanxiaosc** [comment]
@cbigeyes 可以不用计算，我是尝试使用predicate这个信息来指导序列标注，毕竟在run_predicate_classification.py 预测之后，我们已经知道每条句子的关系或者说谓词predicate，那么我们在做序列标注时可以强迫模型做预测时不仅输出序列的标注信息，同时再预测输入的predicate。相关知识你可以百度：自回归模型。
