### ISSUE TITLE
F1

### ISSUE THREAD

**Issue by ZMD177** [yuanxiaosc/Entity-Relation-Extraction#75]
请问训练集和验证集f1怎么计算

**Comment by yuanxiaosc** [comment]
https://github.com/yuanxiaosc/Entity-Relation-Extraction/blob/17bb6ef1b9b4a7b35c3d8020868801d9895a4391/bin/evaluation/evaluate_labeling.py#L67

**Comment by ZMD177** [comment]
您好 感谢您的回复
&nbsp;但是我还是有一些问题
这一行代码是不是对关系抽取也适用呢
还有我跑了代码训练验证关系抽取
验证结果准确率acc只有66









---Original---
From: ***@***.***&gt;
Date: Wed, Dec 29, 2021 14:09 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [yuanxiaosc/Entity-Relation-Extraction] F1 (Issue #75)




 
Closed #75.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
