### ISSUE TITLE
这样release data是违法的吧.....

### ISSUE THREAD

**Issue by herbertchen1** [yuanxiaosc/Entity-Relation-Extraction#8]
这样release data是违法的吧.....

**Comment by yuanxiaosc** [comment]
仅供学习和研究。

**Comment by herbertchen1** [comment]
我个人对这个没什么意见，只是严格来说，这个数据集百度也是标了好多钱的，这样发布，我倒是没啥意见。。。。。。就怕人家找你。。。。我觉得老哥你要不是删了百度网盘把。。。。

**Comment by yuanxiaosc** [comment]
> 我个人对这个没什么意见，只是严格来说，这个数据集百度也是标了好多钱的，这样发布，我倒是没啥意见。。。。。。就怕人家找你。。。。我觉得老哥你要不是删了百度网盘把。。。。

谢谢的建议！

**Comment by lairen2006** [comment]
你好，请问训练数据集能否私下提供一份呢？

**Comment by yuanxiaosc** [comment]
> 你好，请问训练数据集能否私下提供一份呢？

联系我的邮箱即可！
